version: "3"
services:
  oneflix_db:
    image: postgres:9.6
    container_name: "postgres"
    environment:
      - POSTGRES_DB=database
      - POSTGRES_USER=onebitflix
      - POSTGRES_PASSWORD=postgres
      - TZ=America/Sao_Paulo
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    ports:
      - 5432:5432
  redis:
    image: redis
    command: redis-server --requirepass Redis2019!
    ports:
      - "6379:6379"
  pgadmin:
    image: dpage/pgadmin4:4.18
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@postgres.com
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_LISTEN_PORT: 80
    volumes:
      - "./data/pgadmin-data:/var/lib/pgadmin"
    ports:
      - "4000:80"
    links:
      - "oneflix_db:oneflix_db"